### ISSUE TITLE
can not compile on Linux

### ISSUE THREAD

**Issue by tissatussa** [tsoj/Nalwald#1]
i got a warning (which is not severe ?) but then i got an error :

```
$ nimble install malebolgia@1.3.2
Downloading https://github.com/Araq/malebolgia using git
   Warning: Package 'malebolgia' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'malebolgia', but file 'malebolgia_push.nim' is in a directory named 'experiment' instead. This will be an error in the future.
      Hint: If 'experiment' contains source files for building 'malebolgia', rename it to 'malebolgia'. Otherwise, prevent its installation by adding `skipDirs = @["experiment"]` to the .nimble file.
  Verifying dependencies for malebolgia@1.3.2
 Installing malebolgia@1.3.2
  Warning:  A package "malebolgia@1.3.2" with checksum "d8866634d226938200167b614333de900f8c58fd" already exists in the cache.

(base) roelof@roelof-HP-Elite-x2-1012-G2:~/Compiled/Nalwald-19$ nim native Nalwald
Hint: used config file '/home/roelof/.choosenim/toolchains/nim-2.0.6/config/nim.cfg' [Conf]
Hint: used config file '/home/roelof/.choosenim/toolchains/nim-2.0.6/config/config.nims' [Conf]
Hint: used config file 'Nalwald.nims' [Conf]
.........................................................................................................................................................................
/home/roelof/Compiled/Nalwald-19/src/rootSearch.nim(36, 7) Error: type mismatch: got 'tuple[pvList: seq[empty], nodes: int64, canStop: bool]' for '(pvList: @[], nodes: 0'i64, canStop: true)' but expected 'tuple[pvList: seq[Pv], nodes: int, canStop: bool]'
```

i guess it's something simple .. can you fix it ?
i know Nim but i didn't look into the code.
my Nim compiler version is 2.0.6

[ i'm on Xubuntu 22.04 ]

**Comment by tsoj** [comment]
This happens because unfortunately, only Nim compiler versions of 2.1.1 and newer are currently supported.

In case that you have Nim installed via choosenim, you can try to run `choosenim update devel` and then compile Nalwald again.

If you don't have choosenim, you'll need to uninstall Nim from your system and install it as described [here](https://nim-lang.org/install_unix.html) under **Installation using choosenim** (i.e. run `curl https://nim-lang.org/choosenim/init.sh -sSf | sh`). After that is done, close the terminal and open a new window and run `choosenim update devel`. When that is finished, you can try compiling Nalwald again.

**Comment by tissatussa** [comment]
> ..only Nim compiler versions of 2.1.1 and newer are currently supported..

ah .. i could have seen that in the README, sorry .. but i thought i had the newest v2 .. i use `choosenim` but i was not familiar with `update devel`, so thanks for that info. What's the latest 'stable' Nim release ? And why do you use the devel-opment version ? Does it have special features ?

compiling went flawless now and v19 runs fine in CuteChess GUI !

**Comment by tsoj** [comment]
The newest stable release is 2.0.8 if I remember correctly (you can select the newest stable release with `choosenim update stable`). The reason I use the dev version is because it has some nice features that the stable version doesn't yet have (for example the issue you encountered could be solved to work with the stable version, but the code I would have to write for this would be a bit annoying).
